### ISSUE TITLE
Own Prediction Alogrithm: Adjusted KNN With Means

### ISSUE THREAD

**Issue by TamTSE2301** [NicolasHug/Surprise#218]
Hi,

I want to adjust the KNN alogrithm a little bit. My idea is that before you specify k_neighbours by heapq.nlargest, I want to ignore the similarities results that are smaller than a threshold (min_s). Specifically:
```
        for (n,sim,r) in neighbors:
            if sim < min_s:
                sim = 0
```

Of course, I am trying to check the accuracy for this adjustment. However when I built my own alogrithm like your guidlines, i receive the following errors:

> TypeError: compute_similarities() got an unexpected keyword argument 'verbose'

These are the libs I have imported. The code Class Adjusted_KNNWithMeans is the same as your KNNWithMeans; except the change I mentioned above.

```
from surprise import Reader, Dataset, trainset
from surprise import SVD, evaluate, SVDpp
from surprise.model_selection import cross_validate, train_test_split
from surprise.model_selection import train_test_split
from surprise import accuracy
from surprise import PredictionImpossible
from surprise import AlgoBase
from surprise.prediction_algorithms.knns import SymmetricAlgo
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import numpy as np
from six import iteritems
import heapq
```
Thank you very much.

**Comment by NicolasHug** [comment]
What version are you using?
Is the example running when you're not changing anything?

BTW

`self.sim[self.sim < min_s] = 0`

will probably be much faster

**Comment by TamTSE2301** [comment]
Hi. I'm using Python 2.7 on Jupyter

Even when I copy exactly your code of KNN With Means, it still returns the same error message.

![knn](https://user-images.githubusercontent.com/40611425/47218303-98217d00-d3ab-11e8-8574-d02a20c11a0b.JPG)

**Comment by NicolasHug** [comment]
I was talking about the version of surprise/ You missed this part when you created the issue:

#### Versions
Please run the following snippet and paste the output below.

```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import surprise; print("surprise", surprise.__version__)
```

Also, friendly advice: Python 2 is strongly deprecated and is not supported anymore by major scientific packages like numpy and scipy (which surprise depends on)

**Comment by TamTSE2301** [comment]
Thanks for your advice. This is the output:

> Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core
> Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
> [GCC 7.2.0]
> surprise 1.0.6

**Comment by NicolasHug** [comment]
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.

**Comment by NicolasHug** [comment]
Update: the error I'm getting in 1.0.6 is fixed in the current master branch

**Comment by TamTSE2301** [comment]
Hi. On my side, I still receive the same error.

This is my code. If I remained the argument verbose=self.verbose in **self.compute_similarities()**, i would get the error. But if I left it out, my command could run smoothly

What I import:

```
#Built-in functions
from surprise import Reader, Dataset, trainset
from surprise import SVD, evaluate, SVDpp
from surprise.model_selection import cross_validate, train_test_split
from surprise.model_selection import train_test_split
from surprise import accuracy
from surprise import PredictionImpossible
from surprise import AlgoBase, prediction_algorithms, dump
from surprise.prediction_algorithms.knns import SymmetricAlgo
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import numpy as np
from six import iteritems
import heapq
```

My Adjusted_KNNWithMeans:

```
class Adjusted_KNNWithMeans(SymmetricAlgo):

    def __init__(self, k=40, min_k=1, min_s=0.5, sim_options={}, verbose=True, **kwargs):

        SymmetricAlgo.__init__(self, sim_options=sim_options,
                               verbose=verbose, **kwargs)

        self.k = k
        self.min_k = min_k
        self.min_s = min_s


    def fit(self, trainset):

        SymmetricAlgo.fit(self, trainset)
        self.sim = self.compute_similarities(verbose=self.verbose)

        self.means = np.zeros(self.n_x)
        for x, ratings in iteritems(self.xr):
            self.means[x] = np.mean([r for (_, r) in ratings])

        return self

    def estimate(self, u, i):

        if not (self.trainset.knows_user(u) and self.trainset.knows_item(i)):
            raise PredictionImpossible('User and/or item is unkown.')
        
        x, y = self.switch(u, i)

        neighbors = [(x2, self.sim[x, x2], r) for (x2, r) in self.yr[y]]
 
       
        """      
        #Adjustment compared to original KNNWithMeans:

        """
        for i in range(0,len(neighbors)): 
            (n,sim,r)=neighbors[i]
            if sim < self.min_s:
                neighbors[i]= (n,0,r)
  

        """      
        #Below is the same as the origonal KNNWithMeans:

        """      
        
        k_neighbors = heapq.nlargest(self.k, neighbors, key=lambda t: t[1])

        est = self.means[x]

        # compute weighted average
        sum_sim = sum_ratings = actual_k = 0
        for (nb, sim, r) in k_neighbors:
            if sim > 0:
                sum_sim += sim
                sum_ratings += sim * (r - self.means[nb])
                actual_k += 1

        if actual_k < self.min_k:
            raise PredictionImpossible('Not enough neighbours')


        try:
            est += sum_ratings / sum_sim
        except ZeroDivisionError:
            pass  # return mean

        details = {'actual_k': actual_k}
        return est, details

```

My application:

```
#Create Dataset
reader = Reader(rating_scale=(-1000,1000)) #Change to max and min of non-NA data
data = Dataset.load_from_df(inputdata[['Variety','ENV','Value']], reader=reader)
# Create Trainset and Testset
trainset = data.build_full_trainset()
ignoreset, testset = train_test_split(data, test_size=0.2)
sim_options = {'name': 'pearson', 'user_based': True, 'min_support': 5}
algo = Adjusted_KNNWithMeans(min_k=1,k=800,min_s=0.4,sim_options=sim_options)
algo.fit(trainset)
```

My error:

> TypeErrorTraceback (most recent call last)
> <ipython-input-44-189504b23408> in <module>()
>       1 sim_options = {'name': 'pearson', 'user_based': True, 'min_support': 5}
>       2 algo = Adjusted_KNNWithMeans(min_k=1,k=800,min_s=0.4,sim_options=sim_options)
> ----> 3 algo.fit(trainset)
> 
> <ipython-input-41-6ae695402105> in fit(self, trainset)
>      25 
>      26         SymmetricAlgo.fit(self, trainset)
> ---> 27         self.sim = self.compute_similarities(verbose=self.verbose)#verbose=self.verbose
>      28 
>      29         self.means = np.zeros(self.n_x)
> 
> TypeError: compute_similarities() got an unexpected keyword argument 'verbose'
> 

Thank you very much.

**Comment by NicolasHug** [comment]
Thanks for the code.

I can reproduce the issue on 1.0.6, but it looks like it's fixed on the master branch. Are you sure you still get the error when you use the master branch?

In the mean time yeah, remove verbose from the call the `compute_similarities`. Sorry for the bug.

**Comment by TamTSE2301** [comment]
Hi. If you refer to the error of running **examples/building_custom_algorithms/with_baselines_or_sim.py** 
No. I did not get that error.

If I remove verbose from **compute_similarities**. I could run normally

**Comment by NicolasHug** [comment]
No I am referring to the error running your code. Your code runs fine in the current master branch as  far as I can tell

**Comment by TamTSE2301** [comment]
Again. If I still let the verbose argument in **compute_similarities**(), I still get the error.

**Comment by TamTSE2301** [comment]
Yes it works. Thanks.
