### ISSUE TITLE
Jester Dataset no longer at http://eigentaste.berkeley.edu/dataset/jester_dataset_2.zip

### ISSUE THREAD

**Issue by climatebrad** [NicolasHug/Surprise#329]
#### Description
The url for the Jester Dataset has moved from 

`http://eigentaste.berkeley.edu/dataset/jester_dataset_2.zip`
to
`http://eigentaste.berkeley.edu/dataset/archive/jester_dataset_2.zip`

need to change `builtin_datasets.py` line 53 and `dataset.py` line 11.

#### Steps/Code to Reproduce
```
from surprise import Dataset
jokes = Dataset.load_builtin(name='jester')
```
#### Expected Results

Load  `http://eigentaste.berkeley.edu/dataset/archive/jester_dataset_2.zip`

#### Actual Results

```HTTPError: HTTP Error 404: Not Found```

#### Versions
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.1.0
```

**Comment by climatebrad** [comment]
Workaround is to download and unzip `http://eigentaste.berkeley.edu/dataset/archive/jester_dataset_2.zip` and save the .dat files to `~/.surprise_data/jester/`

**Comment by NicolasHug** [comment]
Thanks for the issue!
Fixed by https://github.com/NicolasHug/Surprise/commit/3b3b1f8a7ace086f4527f818d1aae87c9a793966

**Comment by climatebrad** [comment]
Note that the documentation is still wrong 

https://github.com/NicolasHug/Surprise/blob/master/surprise/dataset.py line 11
